[package]
name = "xnor"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
xnor-codegen = { path = "./xnor-codegen" }

[dependencies]
num-traits = "0.2.19"
